/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackCard: typeof import('./src/components/Back-Card.vue')['default']
    BetForm: typeof import('./src/components/BetForm.vue')['default']
    Button: typeof import('./src/components/Button.vue')['default']
    CardTable: typeof import('./src/components/game/CardTable.vue')['default']
    Carousel: typeof import('./src/components/Carousel.vue')['default']
    CashFlow: typeof import('./src/components/CashFlow.vue')['default']
    CommunalPot: typeof import('./src/components/CommunalPot.vue')['default']
    CountdownTimer: typeof import('./src/components/CountdownTimer.vue')['default']
    CreditForm: typeof import('./src/components/CreditForm.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    Form: typeof import('./src/components/Form.vue')['default']
    GameCards: typeof import('./src/components/GameCards.vue')['default']
    GameControls: typeof import('./src/components/game/GameControls.vue')['default']
    GameCta: typeof import('./src/components/GameCta.vue')['default']
    Input: typeof import('./src/components/Input.vue')['default']
    InputLabel: typeof import('./src/components/Input-Label.vue')['default']
    Inputs: typeof import('./src/components/Inputs.vue')['default']
    MainMenu: typeof import('./src/components/dialog/MainMenu.vue')['default']
    MainMenuDialog: typeof import('./src/components/dialog/MainMenuDialog.vue')['default']
    PlayerHand: typeof import('./src/components/PlayerHand.vue')['default']
    PlayerPosition: typeof import('./src/components/PlayerPosition.vue')['default']
    PlayingCard: typeof import('./src/components/PlayingCard.vue')['default']
    PlayingDeck: typeof import('./src/components/decks/PlayingDeck.vue')['default']
    QuitGameDialog: typeof import('./src/components/dialog/QuitGameDialog.vue')['default']
    ResultModal: typeof import('./src/components/ResultModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Timer: typeof import('./src/components/timer.vue')['default']
    TimerDisplay: typeof import('./src/components/TimerDisplay.vue')['default']
  }
}
