/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackCard: typeof import('./src/components/cards/BackCard.vue')['default']
    BetForm: typeof import('./src/components/forms/BetForm.vue')['default']
    Button: typeof import('./src/components/buttons/Button.vue')['default']
    CardTable: typeof import('./src/components/game/CardTable.vue')['default']
    Carousel: typeof import('./src/components/Carousel.vue')['default']
    CashFlow: typeof import('./src/components/currency/CashFlow.vue')['default']
    CashOut: typeof import('./src/components/currency/CashOut.vue')['default']
    CommunalPot: typeof import('./src/components/currency/CommunalPot.vue')['default']
    CountdownTimer: typeof import('./src/components/utilities/CountdownTimer.vue')['default']
    CreditActions: typeof import('./src/components/currency/CreditActions.vue')['default']
    CreditForm: typeof import('./src/components/forms/CreditForm.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElTour: typeof import('element-plus/es')['ElTour']
    ElTourStep: typeof import('element-plus/es')['ElTourStep']
    Form: typeof import('./src/components/Form.vue')['default']
    GameCards: typeof import('./src/components/cards/GameCards.vue')['default']
    GameControls: typeof import('./src/components/game/GameControls.vue')['default']
    GameCta: typeof import('./src/components/gameplay-actions/GameCta.vue')['default']
    GameOverModal: typeof import('./src/components/dialog/GameOverModal.vue')['default']
    Howtoplay: typeof import('./src/components/dialog/howtoplay.vue')['default']
    Input: typeof import('./src/components/Input.vue')['default']
    InputLabel: typeof import('./src/components/Input-Label.vue')['default']
    Inputs: typeof import('./src/components/Inputs.vue')['default']
    MainMenu: typeof import('./src/components/dialog/MainMenu.vue')['default']
    MainMenuDialog: typeof import('./src/components/dialog/MainMenuDialog.vue')['default']
    PlayerForm: typeof import('./src/components/forms/PlayerForm.vue')['default']
    PlayerHand: typeof import('./src/components/game-table/PlayerHand.vue')['default']
    PlayerPosition: typeof import('./src/components/game-table/PlayerPosition.vue')['default']
    PlayerQuitDialog: typeof import('./src/components/dialog/PlayerQuitDialog.vue')['default']
    PlayingCard: typeof import('./src/components/game-table/PlayingCard.vue')['default']
    PlayingDeck: typeof import('./src/components/decks/PlayingDeck.vue')['default']
    QuitGameDialog: typeof import('./src/components/dialog/QuitGameDialog.vue')['default']
    ResultModal: typeof import('./src/components/dialog/ResultModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Timer: typeof import('./src/components/timer.vue')['default']
    TimerDisplay: typeof import('./src/components/TimerDisplay.vue')['default']
  }
}
